#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

error_reporting(0); // To avoid php notices in ParseHtml.php on line 246
define('SITE_URI', 'http://www.statkod.ru/'); // Site URI

use Symfony\Component\Console\Application;
use App\Command\ParserCommand;

$application = new Application('StatCode Parser', '1.0.0');
$command = new ParserCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
